name: tunis_chasse
description: application of hunting in tunisia
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_localization:
  flag:
  awesome_notifications: ^0.7.4+9
  font_awesome_flutter: ^10.1.0
  video_player: ^2.2.6
  carousel_slider:
  label_google_maps_marker:
  flutterflow_ui: 0.2.0
 # point_in_polygon: ^1.0.0
  geolocator: ^9.0.2
  flutter_custom_clippers: ^2.0.0
  xml: ^6.3.0
  location: ^5.0.3
  latlong2: ^0.8.2
  provider:
  shared_preferences: ^2.0.7
  google_maps_flutter:
  flutter_map_marker_cluster: any
  syncfusion_flutter_calendar: ^21.2.10
  time_planner: ^0.1.2+1
  #pusher_channels_flutter: ^2.2.1
  flutter_bloc: ^8.1.5
  flutter_pdfview:
  weather: any
  google_maps_webservice:
  flutter_dotenv: any
 
  web_socket_channel: ^2.1.0






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen:
  build_runner:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/longshoremen.png
    - assets/hunting.mp4
    - assets/sayed.png
    - assets/avatar.jpg
    - assets/levier.jpg
    - assets/sayd.png
    - assets/lois.pdf
    - lib/poly.json
    - assets/.env
    - assets/sayd1.jpg
    - assets/sayd2.jpg
    - assets/sayd3.jpg





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages